export DB_HOST=""
export DB_PORT=""
export DB_NAME=""
export DB_USERNAME=""
export DB_PASSWORD=""
export DB_CONN_STRING="host=${DB_HOST} port=${DB_PORT} user=${DB_USERNAME} password=${DB_PASSWORD} dbname=${DB_NAME}"
export CORS_ORIGINS="*"
export CORS_METHODS="GET,PUT,POST,DELETE,PATCH,OPTIONS,HEAD"
export CORS_HEADERS="Content-Type"
export CORS_EXPOSE_HEADERS="Content-Length"