export DB_HOST="nsync.cfcsbdnasvfb.us-east-1.rds.amazonaws.com"
export DB_PORT="5432"
export DB_NAME="nsyncdb"
export DB_USERNAME="nsync"
export DB_PASSWORD="grupo.nsync"
export DB_CONN_STRING="host=${DB_HOST} port=${DB_PORT} user=${DB_USERNAME} password=${DB_PASSWORD} dbname=${DB_NAME}"
export CORS_ORIGINS="*"
export CORS_METHODS="GET,PUT,POST,DELETE,PATCH,OPTIONS,HEAD"
export CORS_HEADERS="Content-Type"
export CORS_EXPOSE_HEADERS="Content-Length"