# nginx-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-gateway
  template:
    metadata:
      labels:
        app: nginx-gateway
    spec:
      containers:
        - name: nginx-gateway
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
 nginx.conf: |
    events {}
    http {
      server {
            listen 80;

            # Products service proxy
            location /products {
                proxy_pass http://products-service:8081;
            }

            # Delivery service proxy
            location /cep/calculate-days {
                proxy_pass http://cep-estimator:8082;
            }

            # Purchase service proxy
            location /purchases {
                proxy_pass http://purchase-service:8083;
            }

            # CSV Processor service proxy
            location /csv-processor {
                proxy_pass http://upload-csv-service:8084;
            }

            # Catch-all route
            location / {
                return 404;
            }
        }

    }
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-gateway
spec:
  type: NodePort
  selector:
    app: nginx-gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30005