apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-csv-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upload-csv-service
  template:
    metadata:
      labels:
        app: upload-csv-service
    spec:
      containers:
        - name: upload-csv-service
          image: gabcolsil/micro-upload-csv
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_CLIENT
              value: "nsync"
            - name: DATABASE_HOST
              value: "nsync.cfcsbdnasvfb.us-east-1.rds.amazonaws.com"
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_NAME
              value: "nsyncdb"
            - name: DATABASE_USERNAME
              value: "nsync"
            - name: DATABASE_PASSWORD
              value: "grupo.nsync"
            - name: DATABASE_SSL
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: upload-csv-service
spec:
  selector:
    app: upload-csv-service
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8080